### ISSUE TITLE
Self-Hosted modelprompter when Clicking on Blocks doesn't do anything/doesn't perform any function

### ISSUE THREAD

**Issue by Marcus-Arcadius** [ModelPrompter/modelprompter#34]
![image](https://user-images.githubusercontent.com/78793842/193822105-ad94ca2b-f420-4dea-b147-e935a4bd4ee9.png)

**Comment by EverestWonder** [comment]
Thanks for reporting this! I just submitted this project to a few grants so this saved me a lot of awkwardness haha

The default workspace now loads when you visit: https://modelprompter.com/#/block/1b8c46a7-145a-4d23-b076-4d8538afe220

![image](https://user-images.githubusercontent.com/110780894/193954639-a9ee9e03-9bdf-4773-ac4e-7ec4fa0db537.png)

It's still super early though. If you check back in a few weeks this project will totally blow your mind.
Thanks again!
